### ISSUE TITLE
Save alarm info

### ISSUE THREAD

**Issue by hi-im-evab** [topoftheyear/QR-Alarm-Clock#1]
We need to save the info for the alarm so as to display it in MainAlarms and to use it for actually alarm functionality. Find a way to save the info the user sets on the AlarmSettings page.

CURRENTLY: Using MockData class for testing. Will need to be replaced eventually.

**Comment by hi-im-evab** [comment]
https://developer.android.com/training/data-storage/files#WriteInternalStorage

**Comment by jacoby400000** [comment]
done
