### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by spitemim** [topoftheyear/QR-Alarm-Clock#12]
I'm trying to write a FOSS alarm app that forces heavy sleepers to wake up, kind of like Alarmy. If I'm going to base it off an existing project, this looks like a good place to start, but there's no license. It would be really helpful if you were to put a license on this project, but let me know if you want it to stay proprietary.

**Comment by topoftheyear** [comment]
I gave it the Unlicense. Have fun and good luck with your project!
