### ISSUE TITLE
Display alarm's settings in its card on the MainAlarms page

### ISSUE THREAD

**Issue by hi-im-evab** [topoftheyear/QR-Alarm-Clock#2]
Have the card on the MainAlarms page reflect the proper information. For example, if the alarm is set to 6:00pm, make sure it reads 6:00pm on the card.

There is currently only one card, so don't worry too much about multiple alarms. Tackle that later.

**Comment by hi-im-evab** [comment]
This is on its way. The time and whether it's active or not is there.

Still need TODO days of the week it repeats on.

**Comment by jacoby400000** [comment]
done
