### ISSUE TITLE
Make actual alarm clock stuff happen.

### ISSUE THREAD

**Issue by hi-im-evab** [topoftheyear/QR-Alarm-Clock#4]
Probably resolve issue 1 (how to save alarm info) first. 

Android's AlarmManager should probably be your first stop: https://developer.android.com/reference/android/app/AlarmManager

Make something that works :)))

**Comment by hi-im-evab** [comment]
Some tutorials that may be helpful:

https://www.concretepage.com/android/android-alarm-clock-tutorial-to-schedule-and-cancel-alarmmanager-pendingintent-and-wakefulbroadcastreceiver-example

https://javapapers.com/android/android-alarm-clock-tutorial/

**Comment by jacoby400000** [comment]
done
